hw: Add native bootrom to the cluster
pulp-platform/snitch_cluster pull request #168
Opened 2024-07-19 12:28 UTC by fischeti

Adds native bootrom to the cluster instead of fetching from externally. Also adds additional scratch registers to the peripherals which can be used to write the entry point of the binary.

### TODO

- [ ] Decide on the actual bootrom
- [ ] Wait for https://github.com/pulp-platform/snitch_cluster/pull/158. Currently, the testbench uses timing constructs to store the entrypoint to the scratch register. This is only supported in Verilator 5.

2025-01-17 13:30 UTC, colluca requested changes
If I understand correctly, the motivation for this PR is to increase the probability of the Snitch cores to successfully boot at test time, as booting from an internal boot ROM decouples it from external components' reliability, e.g. the system-level interconnect.

While in Occamy the boot ROM was unfortunately located in a different clock domain,  past many interconnect adapters, other defenses could be put in place. For instance, in a system such as FlooOccamy, the boot ROM could occupy just one of the many tiles in the system-level NoC. Unreliability in the components on this path would most likely kill the deployment of any application, independent on the reliability of the boot process. Thus, I still struggle to see the usefulness of this PR.

I think before proceeding with this PR, we need to clearly sort out and weigh its actual advantages and disadvantages. I still don't see any advantage, while I see the following disadvantages:
1) Hardware cost. What is the real cost of adding another port to the wide interconnect? In the thesis, the cost was estimated with a 64-bit wide interconnect configuration. The reported +60 GE sounds unrealistic to me even considering this interconnect, together with the `axi_to_mem` adapter, (small) boot ROM and additional scratch registers.
2) Increased code complexity and maintenance effort.
3) Increased configuration complexity.

If we then choose to go on with this PR, I suggest to make the internal boot feature parametrizable so that the associated hardware cost can be fully removed at configuration time. More comments follow in the review. In any case, we can merge the scratch registers.

2025-01-17 15:21 UTC, paulsc96 commented
I think @fischeti summarized the advantages quite well. Adding this internal boot ROM turns the cluster into a much more autonomous IP, greatly simplifying integration and testing and avoiding fatal integration mistakes. 

It also speeds up initialization in multi-cluster systems *dramatically* (which may be critical for useful large-scale simulation) and saves integrators lots of valuable time in integration and system-level testing.

Finally, it provides a standard interface for interacting with clusters, and the ability to freely repoint execution is a versatile escape hatch in case integration mistakes are made or other problems arise. We actually relied on such an escape hatch through an incidental TLB in an extremely critical chip very recently, so it is a wise choice to integrate such a mechanism straight into the cluster.

2025-01-17 16:01 UTC, colluca commented
> It also speeds up initialization in multi-cluster systems _dramatically_ (which may be critical for useful large-scale simulation) and saves integrators lots of valuable time in integration and system-level testing.
>
I thought about this, but you're gonna run into the same slowdown right after you terminate the first few boot ROM instructions, so I don't think the speedup will be _dramatic_.

> Finally, it provides a standard interface for interacting with clusters, and the ability to freely repoint execution is a versatile escape hatch in case integration mistakes are made or other problems arise. We actually relied on such an escape hatch through an incidental TLB in an extremely critical chip very recently, so it is a wise choice to integrate such a mechanism straight into the cluster.
> 
Well, this is only true if the boot ROM is actually reused, and the integrating systems don't just implement their own (in contrast with what @fischeti said). But in that case the same can be obtained even if we don't instantiate it within each cluster. Couldn't we just provide the boot ROM code and utilities, and test it by integrating it within the testbench, while still not instantiating it in every cluster?

2025-01-17 20:05 UTC, fischeti commented
> > Finally, it provides a standard interface for interacting with clusters, and the ability to freely repoint execution is a versatile escape hatch in case integration mistakes are made or other problems arise. We actually relied on such an escape hatch through an incidental TLB in an extremely critical chip very recently, so it is a wise choice to integrate such a mechanism straight into the cluster.
> 
> Well, this is only true if the boot ROM is actually reused, and the integrating systems don't just implement their own (in contrast with what @fischeti said). But in that case the same can be obtained even if we don't instantiate it within each cluster. Couldn't we just provide the boot ROM code and utilities, and test it by integrating it within the testbench, while still not instantiating it in every cluster?

I changed my mind regarding this. As Paul said, I think it would make more sense to provide the snitch cluster as a standalone IP with a proper default bootrom that makes it easy to integrate into an actual system without the need to implement your custom one (which would still be possible if needed). So the default bootrom should already implement the trampoline functionality with the scratch register.

I don't really see how integrating the generated bootrom into the testbench would improve the situation. The goal in the end is that we can verify the cluster boot procedure standalone, which is only possible if you have a block that combines the cluster and bootrom. Of course, you could write a wrapper around the snitch cluster that includes a bootrom, but this only shifts the complexity and makes integration unnecessarily complex.

I can do a synthesis run to compare the increase in complexity in the Xbar, but some increase is justified in my opinion given that this increases the flexibility and safety of the boot process.

2025-01-27 11:15 UTC, fischeti commented on hw/snitch_cluster/src/snitch_cluster.sv
> +
I removed it

2025-01-27 11:15 UTC, fischeti commented on hw/snitch_cluster/src/snitch_cluster_peripheral/snitch_cluster_peripheral_reg.hjson
> +        },
Is fixed now

2025-01-27 11:17 UTC, fischeti commented on target/snitch_cluster/.rtlbinary
I removed the file

2025-01-27 11:18 UTC, fischeti commented on target/snitch_cluster/test/snitch_bootrom.sv
This will be addressed in another PR, as discussed to improve the snitch cluster integration in general.

2025-01-27 11:19 UTC, fischeti commented on target/snitch_cluster/util/gen_bootrom.py
I moved it to the general util folder

2025-01-27 11:19 UTC, fischeti commented on target/snitch_cluster/Makefile
>  	$(GENERATED_DIR)/bootdata.cc
bootdata is stil needed as mentioned above

2025-01-27 11:20 UTC, fischeti commented on target/snitch_cluster/Makefile
> +GENERATED_RTL_SOURCES += test/snitch_bootrom.sv
will be done in another PR, as mentioned above

2025-01-27 11:20 UTC, fischeti commented on hw/snitch_cluster/src/snitch_cluster_peripheral/Makefile
The file is removed now. Was an issue of rebasing

2025-01-27 17:48 UTC, colluca approved these changes

2025-01-28 08:51 UTC, merged